### ISSUE TITLE
Failing unit tests due to pickle command.

### ISSUE THREAD

**Issue by kapoor1992** [facebookresearch/fastMRI#100]
When running unit tests with "py -m pytest tests", the following errors are encountered which seem to have the same root cause:
![image](https://user-images.githubusercontent.com/17171072/98199933-3fb16f80-1ee1-11eb-818f-55562d9dbc86.png)

The operating system is Windows 10. I also encountered it on OS X Catalina.

**Comment by mmuckley** [comment]
I can reproduce OS X Catalina but not Linux. It's sort of an issue with `pickle`, but `pickle` is only used for multiprocessing, and for some reason on Linux it can pickle this module whereas on MacOS and Windows it can't.

The quick fix if you're just debugging is to set `num_workers` to 0 in your data loader.

I suspect that the culprit is this:

https://github.com/facebookresearch/fastMRI/blob/b9c07e90e1333b3417bef28fcc9137141746cce1/fastmri/data/subsample.py#L56

This might be fixable using the new NumPy random number generator.

Let me know if you get any other information to narrow it down further.

**Comment by vivekiyer** [comment]
Thanks, setting num_workers to 0 works. With this, I am able to run on Windows.

**Comment by kapoor1992** [comment]
Thanks for looking into it @mmuckley (and sorry for accidentally closing this)! So it did solve the issue in the unit tests however I see the same error when running "py train_unet_demo.py":
![image](https://user-images.githubusercontent.com/17171072/98315872-18fd4280-1f8e-11eb-946b-9d65ca25b7ae.png)

I have set num_workers=0 in both train_unet_demo.py, data_module.py, and mri_module.py

**Comment by mmuckley** [comment]
I see. Now it is the ddp accelerator that is using `multiprocessing`. Try setting the `accelerator` parameter to `None`. If that doesn't work, then if I get some time I'll see if I can patch the NumPy `rng` (unless you want to PR it yourself).

**Comment by kapoor1992** [comment]
And that did the trick. For sure I can submit a PR anyways but I'm not sure what you mean by the new numpy RNG? If you mean change the package dependency to 1.19.4 then I tried that and the failures occur still.

**Comment by kapoor1992** [comment]
I have a solution that works with the current accesses around the RNG state, PR opened.

**Comment by jiangwenjie123** [comment]
Hello, take the liberty to bother me, do you have fastmri_examples/varnet and fastmri_examples/unet trained models? Is it easy to share if there are? My email is 729081987@qq.com, or you can put it in Google Cloud Disk, I will download it when that happens, thank you so much!
