### ISSUE TITLE
how to use my own data

### ISSUE THREAD

**Issue by kingaza** [facebookresearch/fastMRI#142]
Hello all,

I would like to train or test my own data by using with the pre-trained model. 
But I dont' know to generate the ismrmrd header.  Could you help me?
What kind of information is necessary?

Thanks a lot.

**Comment by mmuckley** [comment]
You don't really need to output an ISMRMD header - you just need to write a dataloader that returns the expected information. The `SliceData` class is pretty large because of boilerplate, but the core part that extracts information from the header is quite small. https://github.com/facebookresearch/fastMRI/blob/1ee19b58daaa15ff7da0c745f766733a2be6c8b0/fastmri/data/mri_data.py#L268-L272

**Comment by kingaza** [comment]
OK. I would like to have a try...
If ISMRMD header is generated, I can use the same source code for both dataset from fastMRI and my own, 
Anyway, thx a lot.

**Comment by mmuckley** [comment]
Let us know if you need more help.
