### ISSUE TITLE
Submission not approved

### ISSUE THREAD

**Issue by zaccharieramzi** [facebookresearch/fastMRI#17]
I recently submitted a reconstruction to the fastMRI website, but it didn't go through for some reason. This is the feedback I have so far (the icon is not clickable):

![image](https://user-images.githubusercontent.com/6387497/61280544-5ac21280-a7b8-11e9-861c-56cbb7782b01.png)

Is there a way to know why the submission was not approved?

**Comment by tullie** [comment]
Hi @zaccharieramzi,

Your submission is failing because the dropbox link is a preview rather than a direct download. Please change the dl=0 to dl=1 at the end of the link (https://help.dropbox.com/files-folders/share/force-download) and resubmit. Unfortunately there's no automated way to know why it fails.

Thanks,
Tullie

**Comment by zaccharieramzi** [comment]
It worked, thanks!
