### ISSUE TITLE
Varnet Demo failing after one epoch

### ISSUE THREAD

**Issue by kamleshpawar17** [facebookresearch/fastMRI#80]
Hi,

I tried running train_varnet_demo.py, with default parameter.
The training runs fine for the epoch 0 and I also get the checkpoint for this zeroth epoch. 

However for the epoch 1, the training fails in validation step with 'Out of memory error'. 
First, I thought it is an error due to GPU memory (but this should not happen after finishing one epoch).
I tried to change the number of cascade to 4, but still get the same error. I am using GPU with 16 GB RAM.

I tried to figure out, it appears that the dataloader is failing, as I get the following error:
RuntimeError: DataLoader worker (pid 34801) is killed by signal: Killed.
Is there anything happening in dataloader  which may cause this issue?

The error happens only when I am running this on the full brain dataset.
When I use a relatively small (Just a few h5 files) subset of brain dataset, I do not get any error and it runs fine for all the epoch?

**Comment by mmuckley** [comment]
Hello - I'm sorry you're having issues. My first question is: does the "Out of memory error" include anything about CUDA? I just want to verify this is happening on the GPU. Also, what version of PyTorch, PyTorch Lightning are you running?

**Comment by kamleshpawar17** [comment]
Thanks for the quick response!
I think it is cuda throwing the error, following is the snippet from the error log

_File "/usr/local/pytorch/1.5-cuda10/pytorch-1.5-cuda10-venv/lib/python3.7/site packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 34801) is killed by signal: Killed.
During handling of the above exception, another exception occurred:_

I am using PyTorch Lightning 0.9.0 and torch 1.5.0+cu101

**Comment by mmuckley** [comment]
That is not a CUDA memory error. This is a CUDA memory error:

`RuntimeError: CUDA out of memory. Tried to allocate 12.50 MiB (GPU 0; 10.92 GiB total capacity; 8.57 MiB already allocated; 9.28 GiB free; 4.68 MiB cached)`
https://github.com/pytorch/pytorch/issues/16417

In this case it looks like this error log is pointing you elsewhere for the source exception, and the file you're reading the log from was killed because another worker raised an exception. To track down the source you'll have to get the error log for the other process.

As an aside if you're using a workload manager like SLURM make sure you're requesting enough CPU memory so that SLURM doesn't kill your jobs.

**Comment by kamleshpawar17** [comment]
I am using SLURM and running with 32GB CPU memory which potentially may be causing the problem, any idea about how much CPU memory is required?
I will try out with larger CPU memory

**Comment by mmuckley** [comment]
To be clear this is just one possible theory for your issue. We'll need to track down whatever happened in that process to be sure.

In my case I request 50 GB of memory per GPU.

**Comment by kamleshpawar17** [comment]
Thanks @mmuckley 

The cause of the problem was the CPU memory.
I am now able to run with larger CPU memory.

**Comment by mmuckley** [comment]
Great! Let us know if you have any other issues.
